#! /bin/sh

echo "Compiling replicate..."
gcc replicate.c -o replicate
echo "Show any differences for output of 'replicate':"
echo "=========="
./replicate | diff -ur replicate.c -
echo "=========="

echo ""

echo "Compiling replicate1..."
gcc replicate1.c -o replicate1
echo "Show any differences for output of 'replicate1':"
echo "=========="
./replicate1 | diff -ur replicate1.c -
echo "=========="
