#! /bin/sh

echo "Compiling replicate..."
gcc replicate.c -o replicate
echo "Show any differences for output of 'replicate':"
echo "=========="
./replicate > replicate.new.c
diff -ur replicate.c replicate.new.c
echo "=========="
rm -rf replicate.new.c

echo ""

echo "Compiling replicate1..."
gcc replicate1.c -o replicate1
echo "Show any differences for output of 'replicate1':"
echo "=========="
./replicate1 > replicate1.new.c
diff -ur replicate1.c replicate1.new.c
echo "=========="
rm -rf replicate1.new.c
